### ISSUE TITLE
求问大佬报错了是什么原因？说是签名过期了

### ISSUE THREAD

**Issue by TYHHyes** [yiguanxianyu/PKUAutoRun#14]
User
command ReceiveBytes failed to send bytes with: {'DetailedError': 'Error Domain=com.apple.MobileStorage.ErrorDomain Code=-2 "Failed to create path with signature {length = 158, bytes = 0x5061636b 61676520 73697a65 20657863 ... 696e7374 6561642e } in (null)." UserInfo={NSLocalizedDescription=Failed to create path with signature {length = 158, bytes = 0x5061636b 61676520 73697a65 20657863 ... 696e7374 6561642e } in (null).}', 'Error': 'InternalError', 'Status': 'ReceiveBytesAck'}

**Comment by TYHHyes** [comment]
使用的是iPad os15.4版本，之前可以用，现在不知道是哪一步出问题了

**Comment by TYHHyes** [comment]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\construct\core.py", line 213, in stream_tell
    return stream.tell()
AttributeError: 'SafeStreamSocket' object has no attribute 'tell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\PKUAutoRun-main\PKUAutoRun-main\main.py", line 128, in <module>
    main(_distance, _speed)
  File "C:\Users\Admin\Downloads\PKUAutoRun-main\PKUAutoRun-main\main.py", line 25, in main
    device_list = list_devices()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymobiledevice3\usbmux.py", line 388, in list_devices
    mux = create_mux()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymobiledevice3\usbmux.py", line 384, in create_mux
    return MuxConnection.create()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymobiledevice3\usbmux.py", line 165, in create
    response = usbmuxd_response.parse_stream(sock)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\construct\core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\construct\core.py", line 4869, in _parse
    substream = BytesIOWithOffsets.from_reading(stream, length, path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\construct\core.py", line 241, in from_reading
    offset = stream_tell(stream, path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\construct\core.py", line 215, in stream_tell
    raise StreamError("stream.tell() failed", path=path)
construct.core.StreamError: Error in path (parsing)
stream.tell() failed
报错内容
